### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by giovannyreyeso** [stephenlacy/kuberhaus#3]
Why not separate front and back? in two different docker files?

For example:
One docker file serving the static content with nginx and with a "--add-host" call to backend.  this make aviable using "custom ssl config" passing the nginx conf to container in a volume.

http calls made by browser in front send to nginx and nginx make a proxy to backend

**Comment by giovannyreyeso** [comment]
Can u check this branch?: https://github.com/giovannyreyeso/kuberhaus/tree/fixDockerInFront

**Comment by stephenlacy** [comment]
Having one docker container serve both static content and pod metrics makes more sense as it is a much easier deployment, one vs two containers.
If you need it behind an nginx container it is trivial to put the nginx container as a proxy between your browser and the kuberhaus backend container.

**Comment by giovannyreyeso** [comment]
ok. u right thank u!

Have you ever thought about putting it inside a cluster and reading the information from there? and not from the configuration file

**Comment by stephenlacy** [comment]
Yes, I can add support for in-cluster authentication

**Comment by giovannyreyeso** [comment]
Great!. :)

**Comment by stephenlacy** [comment]
@giovannyreyeso it now supports running on kubernetes, the kube.yaml example should work for most clusters

**Comment by giovannyreyeso** [comment]
@stevelacyi will check it out thanku!
